
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Vanp.DAL.Entites
{

using System;
    using System.Collections.Generic;
    
public partial class Request
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Request()
    {

        this.Users = new HashSet<User>();

    }


    public int Id { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedWhen { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedWhen { get; set; }

    public Nullable<int> Order { get; set; }

    public Nullable<bool> Enable { get; set; }

    public string RequestContent { get; set; }

    public Nullable<bool> Approved { get; set; }

    public Nullable<int> ApprovedBy { get; set; }

    public Nullable<int> RequestTypeId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<User> Users { get; set; }

}

}
