
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Vanp.DAL.Entites
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.UserRoles = new HashSet<UserRole>();

        this.BidHistories = new HashSet<BidHistory>();

        this.Products = new HashSet<Product>();

        this.Products1 = new HashSet<Product>();

        this.Products2 = new HashSet<Product>();

        this.Products3 = new HashSet<Product>();

        this.ProductKickeds = new HashSet<ProductKicked>();

        this.ProductKickeds1 = new HashSet<ProductKicked>();

        this.Votes = new HashSet<Vote>();

        this.Votes1 = new HashSet<Vote>();

        this.Wishlists = new HashSet<Wishlist>();

    }


    public int Id { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedWhen { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedWhen { get; set; }

    public Nullable<int> Order { get; set; }

    public Nullable<bool> Enable { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; }

    public string UserPassword { get; set; }

    public string UserAddress { get; set; }

    public string UserPhone { get; set; }

    public string AvartarPath { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public Nullable<System.DateTime> LastLogon { get; set; }

    public Nullable<bool> IsCustomer { get; set; }

    public Nullable<int> Vote { get; set; }

    public Nullable<double> Coin { get; set; }

    public string VerificationCode { get; set; }

    public Nullable<bool> Authorized { get; set; }

    public Nullable<int> VoteUp { get; set; }

    public Nullable<int> VoteDown { get; set; }

    public Nullable<int> RequestId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserRole> UserRoles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BidHistory> BidHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Product> Products { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Product> Products1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Product> Products2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Product> Products3 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductKicked> ProductKickeds { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductKicked> ProductKickeds1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Vote> Votes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Vote> Votes1 { get; set; }

    public virtual Request Request { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Wishlist> Wishlists { get; set; }

}

}
